### ISSUE TITLE
nodejs中模块循环依赖的解决方案

### ISSUE THREAD

**Issue by Gaubee** [Gaubee/blog#65]
一个js文件分享对象是通过`module.exports`来暴露给其它js文件：
- a.js

``` js
module.exports = {name:"a.js"}
```
- b.js

``` js
var a = require("./a.js");
console.log(a.name);
//a.js
```

然而又经常出现这种情况：
**类A中有操作类B的方法，类B中也有操作类A的方法。**两个类彼此依赖于对方的构造函数，比例下面代码的写法：
- A.js

``` js
var B = require("./B");
module.exports = function A(){
    if(!(this instanceof A)){return new A}
    //TODO:....
}
```
- B.js

``` js
var A = require("./A");
module.exports:function B(){
    //balabala......
}
```
- main.js

``` js
var A = require("./A");
```

运行`main.js`，V8的解析顺序是这样的：

> 运行`main.js`，请求`A.js`；运行`A.js`，注意这时仅仅运行到第一行代码，请求`B.js`；运行`B.js`，请求`A.js`。这时候你可以打印这个`A`对象，发现它并不是`A.js`文件中所coding的`function A(){...}`。这就是脚本的通病，因为`A.js`仅仅运行到第一行，还没有运行`module.exports = fun...`。
> 怎么办？我的做法是将`module.exports`赋值语句提取到所有require前面：
> 
> ``` js
> module.exports = A;
> var B = require("./B");
> function A(){...}
> ```
> 
> 如果不理解为何`function A`的声明顺序在使用顺序后面的，应该去了解一下js预编译机制。当然也可以这么写：
> 
> ``` js
> module.exports = function A(){...};
> var B = require("./B");
> ```
> 
> 如果要和其它语言保持一样的风格。

非`function`对象的话也差不多，`require`写在`module.exports`后面：

``` js
module.exports = {
    foo:function(){ return new B; }
}
var B = require("./B");
```

如果想依赖的声明提前的话，可以这样子：

``` js
var B = require("./B");
var A = {
    foo:function(){ return new B; }
};
module.exports.__proto__ = A;
```

这是使用原型链的原理，不理解的请自行补习JS原型链。

---

下面给出一个完整的例子来说明这个问题：
**错误写法：**
- A.js

``` js
var B = require("./B");
module.exports = {
    name:"A",
    foo:function(){
        B.foo();
    }
}
```

B.js

``` js
var A = require("./A");
module.exports = {
    name:"B",
    foo:function(){
        console.log(A.name);
    }
}
```

AB.js

``` js
var A = require("./A");
A.foo()
```

运行结果为：

```
undefined
[Finished in 0.1s]
```

**正确写法：**
- A.js

``` js
var B = require("./B");
module.exports.__proto__ = {
    name:"A",
    foo:function(){
        B.foo();
    }
}
```

B.js

``` js
var A = require("./A");
module.exports.__proto__ = {
    name:"B",
    foo:function(){
        console.log(A.name);
    }
}
```

AB.js

``` js
var A = require("./A");
A.foo()
```

运行结果为：

```
A
[Finished in 0.1s]
```

**Comment by ghostcode** [comment]
不要重写 module.exports 就可以
