### ISSUE TITLE
理解KOA

### ISSUE THREAD

**Issue by Gaubee** [Gaubee/blog#90]
## 理解KOA的设计原理和中间件的协作方式。

首先注意这几点：
- 中间件默认是在一条一维的生产线上。
- KOA是WEB框架

所以，`yield next`的目的是什么？可以这样说：
把必经的中间件写在最前面，
然后这些必经的中间件在一层层yield后，到了开发者自己的路由层，在这里，开发者就根据path、method或者其它自定义的方式来区分了。这里类似在做一个switch的分发。

所以这里要用yield next还是用return就很重要。
- yield next说明要跳过，在开发者自己的路由层，往往就是return yield next，来表明这个不是自己的货。
- 直接return就说明不再调用其它的中间层，那么上面已经执行的中间件就开始收尾。
## next是什么

这里理解next是很重要的。毕竟这个是一个核心的东西。
这里把代码流程都剥开看。
先看[koa-compose](https://github.com/koajs/compose)的核心代码是怎么调用中间件的：

``` js
function compose(middleware){
  return function *(next){
    if (!next) next = noop();

    var i = middleware.length;

    while (i--) {
      next = middleware[i].call(this, next); // 这里
    }

    yield *next;
  }
}
```

注意这里call并不是调用函数，而是调用生成器Generator，那个while用处就是把这些中间件的next的位置都给固定了。
还有注意，compose返回的是一个Generator。

接下来再看[koa](https://github.com/koajs/koa)的代码：

``` js
app.callback = function(){
  var fn = this.experimental
    ? compose_es7(this.middleware)
    : co.wrap(compose(this.middleware)); // 这里
  var self = this;

  if (!this.listeners('error').length) this.on('error', this.onerror);

  return function(req, res){
    res.statusCode = 404;
    var ctx = self.createContext(req, res);
    onFinished(res, ctx.onerror);
    fn.call(ctx).then(function () {
      respond.call(ctx);
    }).catch(ctx.onerror);
  }
};
```

看这里`co.wrap`，这是做什么？，看[co](https://github.com/tj/co)的代码：

``` js
co.wrap = function (fn) {
  createPromise.__generatorFunction__ = fn;
  return createPromise;
  function createPromise() {
    return co.call(this, fn.apply(this, arguments)); // 这里
  }
};
```

这里做的，是把compose返回的Generator生成实例。
然后要理解的就是co怎么调用了。
**co返回的是一个Promise对象**。

而co怎么运作，这里就不详说，因为那个并没有和此文有直接关系，这里简单说一下co的yield所接受的是什么，这是官方给出的文档：

``` md
The yieldable objects currently supported are:

promises
thunks (functions)
array (parallel execution)
objects (parallel execution)
generators (delegation)
generator functions (delegation)
```

上面就是这里要说的**next是什么**
我介绍一下最简单的`thunks`：

``` js
app.use(function*(next) {
    var self = this;
     function thunks(next) {
        console.log(next.toString())
        setTimeout(function() {
            next(null, self.status = 408); // err result
        }, 1000);
    }
    var res = yield thunks;
    yield next;
    console.log(res)
});
```

**Comment by renaesop** [comment]
核心就是koa-compose吧。个人觉得最巧妙之处就是用反向遍历时，把后一个中间件转化为generator用参数，传递给前一个中间件。再由前一个generator觉得是不是用yield next展开。

co感觉与这个关系也蛮大的，理论上只能yield *next，但是实际上在koa里面可以写yield next，原因是co会对generator进行递归的包装……
