### ISSUE TITLE
React+Redux学习笔记

### ISSUE THREAD

**Issue by Gaubee** [Gaubee/blog#92]
关于Redux，接口看来就是下面这几个：

```
export {
  createStore,
  combineReducers,
  bindActionCreators,
  applyMiddleware,
  compose
}
```
### createStore

store对象的接口有以下几个：

``` js
return {
  dispatch,
  subscribe,
  getState,
  replaceReducer
}
```
#### dispatch

``` js
lock = true;// 加锁，dispatch里头不可以有dispatch
state = recuder(state , action);
lock = false;

run_listeners();// 执行监听
```

这里state对象实际上是一个旧copy对象的副本，所以每一次dispatch，实际上的性能损耗和state的大小有关，这点会成为**瓶颈**。

有一些误导人的写法Reducer写法是使用if-else去判断action.type，这样是不好的。小应用我不说，到大型应用里面就会引发性能问题，你要确保你的应用保持60fps的话，大型应用乱用`if-else/swtich-case`等原子操作是有可能会直接带来几毫秒的损耗，我测试的数据是`Chrome 48.0.2564.97 m | x64`，判断语句的数量达到100000的话，每一次花费的时间最多需要35ms。而如果使用Object-hash，即便100000，每一次花费的时间只需要 12/1000000ms上下。虽然一般的应用不会达到100000的`if-else/swtich-case`的条件判断数量，但这只是在说其中一个方面所映射出来的js编程习惯，大型应用中走的`if-else/swtich-case`应该不会那么多，但是大量原子级的操作在执行这个Reducer的时候，是一个很考究编程习惯，可能一个不好的编程习惯就会导致整个Reducer的执行增加了零点几毫秒，多人协作开发，堆积的影响会很大。

**Comment by Gaubee** [comment]
为什么Redux需要Reducer拷贝一份数据而不是直接修改源对象后返回，原因是这个：
在[src/combineReducers.js](https://github.com/reactjs/redux/blob/master/src/combineReducers.js)里面
```js

      var previousStateForKey = state[key]
      var nextStateForKey = reducer(previousStateForKey, action)
//...

      hasChanged = hasChanged || nextStateForKey !== previousStateForKey
```

如果是引用对象，直接修改这个引用对象并返回会导致即便是改动了，hasChanged 还是以为没改变。这回导致数据不更新的。

**Comment by Gaubee** [comment]
### bindActionCreators

action的创建用，需要再调用dispatch来进行执行，所以这个函数只是把这两步合成一部。
```js
const action =createAction( data );
/* ==> {
    type,
    data:data;
}*/
store.dispatch(action);

// ==>

createActionAndDispatch( data );

```

**Comment by Gaubee** [comment]
### applyMiddleware

他们说Redux的接口都是精挑细选的，好吧。这个接口核心就是这样的：
```js
// 原本：
var store = createStore(reducer, initialState, enhancer)
// 在原本的基础上
middleware({
      getState: store.getState,
      dispatch: (action) => dispatch(action)
    })
```

**Comment by Gaubee** [comment]
### compose

把好多函数合成一个函数

**Comment by Gaubee** [comment]
为什么要用单向数据流，今天遇到一个情景是这样的：
![image](https://cloud.githubusercontent.com/assets/2151644/13523442/73862dfc-e230-11e5-9ae6-c8d3f0fdbf36.png)

所以问题就来了。
在白色背景的内容部分是一个swipeable的组件。

在进行swipe的时候，头部的index也需要改动。

----

而按照渲染顺序， AppBar是先执行渲染的。虚拟DOM的渲染是一个线性执行的过程，AppBar渲染完成后，开始渲染swipeable组件，swipeable的render中如果加入了对AppBar渲染的代码，就会造成死循环。
即便是吧渲染写在事件中：
![image](https://cloud.githubusercontent.com/assets/2151644/13524090/1a205964-e234-11e5-9b18-b0bb1fd7c2c0.png)
事件的触发也无法立即更新视图，而是会等到下一次数据改动的时候渲染这一次的改动。

----

所以，根据react这个尿性。才有flux和redux这些辅助型的东西，把数据存储在最顶层，然后自上而下的进行更新。

**Comment by Gaubee** [comment]
不过话说回来，使用Redux或者flux并不能直接解决上面那种代码的问题，理解**单向数据**是很重要的，脑子里面要有React渲染的流程，所以即便是用了Redux，上面那代码的结构也不能说直接解决问题。

按照单项数据流的原理，这个AppBarChildren本来就应该在AppBar里面定义好，然后向**父级**提供一个数据接口来渲染这个Children，然后由AppBar的调用者，也就是上面说的**父级**定义一个changeTabIndex的函数，分别传入AppBar与AppContent中。然后AppContent（也就是Swipe）执行changeTabIndex后，父级统一更改AppBar与AppContent的props里头的tabIndexValue。

----

操蛋，我就不想这么做，因为之所以这样写代码，把AppBar的Children放在AppContent里面，为了就是在让多个页面共用一个AppBar的情况下，又要确保AppBar的灵活，所以说把changeTabIndex放到父级，是我不想要的，因为我要确保这个AppContent的灵活性。

所以再思考了渲染原理后，我做了一行代码的改动，解决了：

![image](https://cloud.githubusercontent.com/assets/2151644/13530585/087b186a-e25d-11e5-9b6a-946306084048.png)

如图，只要把setState的执行放到setAppBarChildren后面，完美解决。

**Comment by muzea** [comment]
tab index的问题看上去更像是架构设计的问题，并不是React的缺陷
