### ISSUE TITLE
关于春运抢票系统改进的一些想法

### ISSUE THREAD

**Issue by Gaubee** [Gaubee/blog#93]
春运的抢票应该换成系统托管安排的模式，现有的抢票其实就是一种实时思想，与现实的情景不是完全契合。

春运的票就那么多，所以只要提前一个月告诉系统在某个时间段你要从哪里去哪里，和抢票软件一样的操作设定。完后系统就根据这些数据通过算法来安排，这样就省去了系统预估站点所需票量的计算还有成吨的刷票系统的轮询流量；坏处是不方面退票，因为这就是预编译的方式替代动态执行的方式（说是坏处，但如果使用这种方式可以大幅度减少黄牛的存在，因为它做的就是黄牛的工作，而且不透明、安全、快速）。

所以比较适合春运这种大规模，因为预编译，所以铁道部可以准确安排每一个站点所需要的车厢数，合理协调（现有系统是预判的，所以会出现当前站点没票，而提前几站有票的这种bug）。也因为预编译，票需要提前可设定的几天来进行不可退票式的发放车票。

这种设定是基于每个人都愿意给出一定的调配空间，互相让利的前提下才有的可能。

像有些人买到票了，但其实他可以其它时间段走，而有的人想在这个时间段走，导致这种互利关系不存在，而系统也不知道，只能通过往年的大数据来估算这个站点需要的车厢座位是多少。如果系统知道这些需求压力的话，调配一下，是有可能多安排出一两节车厢的。

**Comment by Luqir** [comment]
说的有道理，反正我没听懂  = 。=
